# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', versatileimagefield.fields.VersatileImageField(upload_to='project_images/', verbose_name='Image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('Volunteer', 'Volunteer'), ('Work', 'Work'), ('Education', 'Education'), ('4Winter', 'Winter')], max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('organization', models.CharField(max_length=128)),
            ],
        ),
    ]
