# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='_type',
            field=models.CharField(choices=[('Volunteer', 'Volunteer'), ('Work', 'Work'), ('Education', 'Education'), ('Skills', 'Skills')], max_length=128),
        ),
        migrations.AlterField(
            model_name='resume',
            name='organization',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
