# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170529_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name_plural': 'Resume'},
        ),
    ]
