# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170529_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
