# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 21:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170529_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 29, 17, 42, 33, 70993)),
        ),
    ]
