# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170529_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 29, 22, 3, 52, 509940, tzinfo=utc)),
        ),
    ]
