# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170531_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='http://alxhghs.pythonanywhere.com'),
            preserve_default=False,
        ),
    ]
