# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('img', versatileimagefield.fields.VersatileImageField(upload_to='blog_images/', verbose_name='Image')),
                ('text', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
